import React, { useState } from 'react';
import { Activity, ArrowUpRight, ArrowDownRight, Clock, Shield, Sliders, CheckCircle2 } from 'lucide-react';
import { INITIAL_SIGNALS } from '../tradingData';
import { AssetClass, SignalItem } from '../types';

export const LiveSignalsView: React.FC = () => {
  const [filterAsset, setFilterAsset] = useState<string>('All');
  const [signals, setSignals] = useState<SignalItem[]>(INITIAL_SIGNALS);
  const [selectedSignal, setSelectedSignal] = useState<SignalItem | null>(null);
  const [executedIds, setExecutedIds] = useState<Set<number>>(new Set());

  const filtered = filterAsset === 'All' ? signals : signals.filter((s) => s.asset === filterAsset);

  const handleExecute = (id: number) => {
    setExecutedIds((prev) => new Set(prev).add(id));
  };

  return (
    <div className="space-y-6">
      {/* Top Filter & Overview Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-[#0f1524] border border-slate-800 p-4 rounded-xl">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400">
            <Activity className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-white">Live AI Signal Feeds</h2>
            <p className="text-xs text-slate-400">
              Generated by BVNL orderbook flow analysis &amp; WTDA multi-resolution wavelets
            </p>
          </div>
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-1.5 bg-slate-900 border border-slate-800 p-1 rounded-xl text-xs">
          {['All', 'Crypto', 'Forex', 'Equities', 'Commodities'].map((asset) => (
            <button
              key={asset}
              onClick={() => setFilterAsset(asset)}
              className={`px-3 py-1.5 rounded-lg font-medium transition cursor-pointer ${
                filterAsset === asset
                  ? 'bg-indigo-600 text-white font-bold'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {asset}
            </button>
          ))}
        </div>
      </div>

      {/* Grid of Signals Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {filtered.map((s) => {
          const isLong = s.status === 'LONG';
          const isShort = s.status === 'SHORT';
          const isExecuted = executedIds.has(s.id);

          return (
            <div
              key={s.id}
              className="rounded-xl border border-slate-800 bg-[#0f1524] p-5 flex flex-col justify-between hover:border-slate-700 transition"
            >
              <div>
                {/* Header */}
                <div className="flex items-start justify-between">
                  <div>
                    <h3 className="text-base font-bold text-white">{s.symbol}</h3>
                    <p className="text-[11px] text-slate-500">{s.asset} · {s.timeframe}</p>
                  </div>
                  <span
                    className={`px-2.5 py-0.5 rounded text-xs font-bold ${
                      isLong
                        ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                        : isShort
                        ? 'bg-red-500/10 text-red-400 border border-red-500/20'
                        : 'bg-slate-800 text-slate-400'
                    }`}
                  >
                    {s.status}
                  </span>
                </div>

                {/* Confidence Bar */}
                <div className="mt-4 space-y-1">
                  <div className="flex justify-between text-xs">
                    <span className="text-slate-500">AI Confidence</span>
                    <span className="font-mono text-indigo-400 font-bold">{s.confidence}%</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full bg-indigo-500 rounded-full" style={{ width: `${s.confidence}%` }} />
                  </div>
                </div>

                {/* Pricing Levels */}
                <div className="mt-4 grid grid-cols-3 gap-2 bg-slate-900/60 p-2.5 rounded-lg border border-slate-800/60 text-center font-mono">
                  <div>
                    <p className="text-[10px] text-slate-500 uppercase">Entry</p>
                    <p className="text-xs text-white font-semibold">${s.entry.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-[10px] text-emerald-500 uppercase">Target</p>
                    <p className="text-xs text-emerald-400 font-semibold">${s.target.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-[10px] text-red-500 uppercase">Stop</p>
                    <p className="text-xs text-red-400 font-semibold">${s.stop.toLocaleString()}</p>
                  </div>
                </div>

                {/* Model Attribution */}
                <div className="mt-3 flex items-center justify-between text-xs text-slate-500">
                  <span>Model: <strong className="text-slate-300 font-normal">{s.model}</strong></span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {s.age}
                  </span>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="mt-5 pt-3 border-t border-slate-800 flex items-center gap-2">
                <button
                  onClick={() => setSelectedSignal(s)}
                  className="flex-1 py-1.5 text-xs text-slate-400 hover:text-white rounded-lg border border-slate-700/60 hover:border-slate-600 transition cursor-pointer"
                >
                  Details
                </button>
                <button
                  onClick={() => handleExecute(s.id)}
                  disabled={isExecuted}
                  className={`flex-1 py-1.5 text-xs font-semibold rounded-lg transition cursor-pointer flex items-center justify-center gap-1 ${
                    isExecuted
                      ? 'bg-emerald-600/20 text-emerald-400 border border-emerald-500/30'
                      : 'bg-indigo-600 hover:bg-indigo-500 text-white'
                  }`}
                >
                  {isExecuted ? (
                    <>
                      <CheckCircle2 className="w-3 h-3" />
                      Routed
                    </>
                  ) : (
                    'Execute'
                  )}
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Signal Details Modal */}
      {selectedSignal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-xs p-4">
          <div className="w-full max-w-lg bg-[#0f1524] border border-slate-800 rounded-2xl p-6 text-white space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div>
                <h3 className="text-lg font-bold">{selectedSignal.symbol} Detailed Signal Breakdown</h3>
                <p className="text-xs text-slate-400">{selectedSignal.model} · {selectedSignal.timeframe} timeframe</p>
              </div>
              <button
                onClick={() => setSelectedSignal(null)}
                className="text-slate-400 hover:text-white text-sm px-2 py-1 rounded-lg bg-slate-800"
              >
                ✕
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div className="flex justify-between py-1 border-b border-slate-800">
                <span className="text-slate-400">Direction</span>
                <span className="font-bold text-emerald-400">{selectedSignal.status}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800">
                <span className="text-slate-400">Confidence Score</span>
                <span className="font-mono text-indigo-400 font-bold">{selectedSignal.confidence}%</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800">
                <span className="text-slate-400">Optimal Limit Entry</span>
                <span className="font-mono">${selectedSignal.entry}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800">
                <span className="text-slate-400">Take Profit (Target 1)</span>
                <span className="font-mono text-emerald-400">${selectedSignal.target}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800">
                <span className="text-slate-400">Hard Stop Loss</span>
                <span className="font-mono text-red-400">${selectedSignal.stop}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800">
                <span className="text-slate-400">Risk-to-Reward Ratio</span>
                <span className="font-mono text-cyan-400 font-bold">1 : 2.8</span>
              </div>
            </div>

            <div className="pt-2 flex justify-end gap-2">
              <button
                onClick={() => setSelectedSignal(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-semibold cursor-pointer"
              >
                Close
              </button>
              <button
                onClick={() => {
                  handleExecute(selectedSignal.id);
                  setSelectedSignal(null);
                }}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-semibold cursor-pointer"
              >
                Route to Execution Engine
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
